### ISSUE TITLE
Check Resource Update Failure

### ISSUE THREAD

**Issue by QSlotus** [Hiro420/FetchHotfix#3]
I managed to get the hotfix url using the project, but when I apply it to lunarcore, it doesn't work properly
I was able to log in to my lunarcore account normally, but when it started doing a check for game resource updates, it reported an error
Here is the error message
![d89fabde4889a09e786d23017d38c73d](https://github.com/Hiro420/FetchHotfix/assets/109905194/e8795329-5fcc-4f34-9c2a-84939a9d13e9)

![eca0ae2b02c97b5f866a4d687c2a5748](https://github.com/Hiro420/FetchHotfix/assets/109905194/a4b11fa8-3208-4ba0-99aa-93d8887295ef)

![c54fb99164442e5ab023980efbc25c47](https://github.com/Hiro420/FetchHotfix/assets/109905194/e7f55bd7-2275-43e7-a1da-281d0d883767)

**Comment by QSlotus** [comment]
( When I use a hotfix url that someone else got via a packet grab, it works fine )

**Comment by Hiro420** [comment]
can you send me the hotfix.json?

**Comment by QSlotus** [comment]
Here's the hotfix url via your project

```json
{
  "assetBundleUrl": "https://autopatchcn.bhsr.com/asb/V2.2Live/output_5766530_c50f240bb5",
  "exResourceUrl": "https://autopatchcn.bhsr.com/design_data/V2.2Live/output_7139860_0a19e93c1b06",
  "luaUrl": "https://autopatchcn.bhsr.com/lua/V2.2Live/output_5814871_124d3e577a",
  "ifixUrl": "https://autopatchcn.bhsr.com/ifix/V2.2Live/output_7093310_a64f702b9cf7",
  "customMdkResVersion": 0,
  "customIfixVersion": 0
}
```

**Comment by Hiro420** [comment]
should be fixed now, try again

**Comment by QSlotus** [comment]
it works, thanks!
